[[redirects]]
  from = "https://nanahandresaputra.netlify.app/*"
  to = "https://nana-handre-saputra.my.id/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.conditions]
    Host = "nanahandresaputra.netlify.app"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
